# Generated by Django 5.1.6 on 2025-04-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
